In [134]:
import pandas as pd 
from pathlib import Path

In [117]:
folder_path = Path(r"C:\Users\F0040RP\Documents\DartLib_RDS\persConsultations\WoS\resilience")

In [118]:
df = pd.read_csv(Path(folder_path, "resilience1_500.txt"), encoding = "utf-8", sep = "\t")
df.head()

,PT,AU,BA,BE,GP,AF,BF,CA,TI,SO,...,WC,WE,SC,GA,PM,OA,HC,HP,DA,UT
0,J,"Adekola, J; Clelland, D",NaN,NaN,NaN,"Adekola, Josephine; Clelland, David",NaN,NaN,Two sides of the same coin: Business resilienc...,JOURNAL OF CONTINGENCIES AND CRISIS MANAGEMENT,...,Management,Social Science Citation Index (SSCI),Business & Economics,KM7AN,NaN,Green Accepted,NaN,NaN,2023-08-03,WOS:000479973700001
1,J,"Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...",NaN,NaN,NaN,"Mochizuki, Junko; Keating, Adriana; Liu, Wei; ...",NaN,NaN,An overdue alignment of risk and resilience? A...,DISASTERS,...,"Environmental Studies; Social Sciences, Interd...",Social Science Citation Index (SSCI),Environmental Sciences & Ecology; Social Scien...,FY5FG,28682497.0,Bronze,NaN,NaN,2023-08-03,WOS:000426851400008
2,J,"Olsson, P; Galaz, V; Boonstra, WJ",NaN,NaN,NaN,"Olsson, Per; Galaz, Victor; Boonstra, Wiebren J.",NaN,NaN,Sustainability transformations: a resilience p...,ECOLOGY AND SOCIETY,...,Ecology; Environmental Studies,Science Citation Index Expanded (SCI-EXPANDED)...,Environmental Sciences & Ecology,AY2TA,NaN,"gold, Green Submitted",Y,N,2023-08-03,WOS:000347440700010
3,J,"Saikia, P; Beane, G; Garriga, RG; Avello, P; E...",NaN,NaN,NaN,"Saikia, Panchali; Beane, George; Garriga, Rica...",NaN,NaN,City Water Resilience Framework: A governance ...,SUSTAINABLE CITIES AND SOCIETY,...,Construction & Building Technology; Green & Su...,Science Citation Index Expanded (SCI-EXPANDED),Construction & Building Technology; Science & ...,1N5LO,NaN,hybrid,NaN,NaN,2023-08-03,WOS:000800697400001
4,C,"Viscu, LI",NaN,"Ionescu, S; Tomita, M; Cace, S",NaN,"Viscu, L-, I",NaN,NaN,Resilience indicators in psychotherapy,SECOND WORLD CONGRESS ON RESILIENCE: FROM PERS...,...,"Psychiatry; Psychology; Psychology, Multidisci...",Conference Proceedings Citation Index - Scienc...,Psychiatry; Psychology,BB2SB,NaN,NaN,NaN,NaN,2023-08-03,WOS:000342208700230

In [119]:
df.loc[0:5, 'AU']

0                              Adekola, J; Clelland, D
1    Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...
2                    Olsson, P; Galaz, V; Boonstra, WJ
3    Saikia, P; Beane, G; Garriga, RG; Avello, P; E...
4                                            Viscu, LI
5                          Walsh-Dilley, M; Wolford, W
Name: AU, dtype: object

In [120]:
subdf = df.loc[:, ['AU', 'TI', 'SO', 'UT', 'CR', 'NR', 'TC', 'Z9']]
subdf.shape

(500, 8)

In [121]:
subdf.head()

,AU,TI,SO,UT,CR,NR,TC,Z9
0,"Adekola, J; Clelland, D",Two sides of the same coin: Business resilienc...,JOURNAL OF CONTINGENCIES AND CRISIS MANAGEMENT,WOS:000479973700001,"Adekola J, 2018, INT J DISAST RISK RE, V31, P4...",49,35,37
1,"Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...",An overdue alignment of risk and resilience? A...,DISASTERS,WOS:000426851400008,"Ainuddin S, 2012, NAT HAZARDS, V63, P909, DOI ...",136,31,31
2,"Olsson, P; Galaz, V; Boonstra, WJ",Sustainability transformations: a resilience p...,ECOLOGY AND SOCIETY,WOS:000347440700010,"Adger WN, 2005, ECOL SOC, V10; Anderies JM, 20...",127,317,318
3,"Saikia, P; Beane, G; Garriga, RG; Avello, P; E...",City Water Resilience Framework: A governance ...,SUSTAINABLE CITIES AND SOCIETY,WOS:000800697400001,"Adams C.A., 2020, SUSTAINABLE DEV GOAL; Alegre...",39,16,16
4,"Viscu, LI",Resilience indicators in psychotherapy,SECOND WORLD CONGRESS ON RESILIENCE: FROM PERS...,WOS:000342208700230,"[Anonymous], 1997, PSYCHOTHERAPY IMPOSS; [Anon...",5,1,1

In [122]:
authors_only_df = subdf['AU'].str.split("; ", expand = True)

In [123]:
authors_only_df.describe()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
count,500,396,287,168,106,69,43,24,18,12,...,7,5,5,2,2,2,2,2,2,1
unique,456,376,277,160,104,69,43,24,18,12,...,7,5,5,2,2,2,2,2,2,1
top,"Prayag, G","Baban, A","Goonetilleke, A","Ziyath, AM","Mechler, R","Fisher, S","Leten, J","Ruiz-Apilanez, I","Shouler, M","Ward, R",...,"Sakurai, M","Sarriegi, JM","Serrano, N","Shogren, J","Sterner, T","Vincent, JR","Walker, B","Xepapadeas, A","de Zeeuw, A","Virapongse, A"
freq,5,3,3,4,2,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [124]:
authors_only_df.columns = [str(int(col) + 1) for col in authors_only_df.columns]
authors_only_df.head(2)

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
0,"Adekola, J","Clelland, D",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"Mochizuki, J","Keating, A","Liu, W","Hochrainer-Stigler, S","Mechler, R",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [125]:
authorsdf = pd.concat([subdf, authors_only_df], axis = 1)
authorsdf.head(2)

,AU,TI,SO,UT,CR,NR,TC,Z9,1,2,...,14,15,16,17,18,19,20,21,22,23
0,"Adekola, J; Clelland, D",Two sides of the same coin: Business resilienc...,JOURNAL OF CONTINGENCIES AND CRISIS MANAGEMENT,WOS:000479973700001,"Adekola J, 2018, INT J DISAST RISK RE, V31, P4...",49,35,37,"Adekola, J","Clelland, D",...,None,None,None,None,None,None,None,None,None,None
1,"Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...",An overdue alignment of risk and resilience? A...,DISASTERS,WOS:000426851400008,"Ainuddin S, 2012, NAT HAZARDS, V63, P909, DOI ...",136,31,31,"Mochizuki, J","Keating, A",...,None,None,None,None,None,None,None,None,None,None

In [126]:
authors_longdf = pd.melt(authorsdf, id_vars=['AU', 'TI', 'SO', 'UT', 'CR', 'NR', 'TC', 'Z9'])

In [127]:
authors_longdf.tail()

,AU,TI,SO,UT,CR,NR,TC,Z9,variable,value
11495,"Gupta, S; McCarthy, PJ",The sporting resilience model: A systematic re...,FRONTIERS IN PSYCHOLOGY,WOS:000907148800001,"Adam R., 2019, J QUAL RES SPORT STU, V13, P61;...",182,0,0,23,None
11496,"Nemeth, DG; Olivier, TW",Environmental Resilience,INNOVATIVE APPROACHES TO INDIVIDUAL AND COMMUN...,WOS:000416155500007,"Adelson J., 2016, ADVOCATE, p4A; Adelson J., 2...",26,0,0,23,None
11497,"Dumitru, R; Turliuc, MN",Construction and validation of the resilience ...,SECOND WORLD CONGRESS ON RESILIENCE: FROM PERS...,WOS:000342208700201,"[Anonymous], 1990, DEV PSYCHOPATHOL, DOI [10.1...",16,0,0,23,None
11498,"Makhnach, AV",HUMAN RESILIENCE AS RESEARCH OBJECT IN PSYCHOLOGY,PSIKHOLOGICHESKII ZHURNAL,WOS:000410461400001,"[Anonymous], TEORIYA PRAKTIKA OBS; [Anonymous]...",38,5,6,23,None
11499,"Grove, K; Barnett, A; Cox, S",Designing justice? Race and the limits of reco...,GEOFORUM,WOS:000592912200015,"Anderson B, 2020, PROG HUM GEOG, V44, P621, DO...",85,14,14,23,None

In [128]:
authors_longdf = authors_longdf.rename(columns = {"variable": "author_pos", "value": "author"})
authors_longdf.head(3)

,AU,TI,SO,UT,CR,NR,TC,Z9,author_pos,author
0,"Adekola, J; Clelland, D",Two sides of the same coin: Business resilienc...,JOURNAL OF CONTINGENCIES AND CRISIS MANAGEMENT,WOS:000479973700001,"Adekola J, 2018, INT J DISAST RISK RE, V31, P4...",49,35,37,1,"Adekola, J"
1,"Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...",An overdue alignment of risk and resilience? A...,DISASTERS,WOS:000426851400008,"Ainuddin S, 2012, NAT HAZARDS, V63, P909, DOI ...",136,31,31,1,"Mochizuki, J"
2,"Olsson, P; Galaz, V; Boonstra, WJ",Sustainability transformations: a resilience p...,ECOLOGY AND SOCIETY,WOS:000347440700010,"Adger WN, 2005, ECOL SOC, V10; Anderies JM, 20...",127,317,318,1,"Olsson, P"

In [129]:
print(authors_longdf.shape)
authors_longdf = authors_longdf.dropna(subset = ["author"])
print(authors_longdf.shape)

(11500, 10)
(1683, 10)

In [130]:
authors_longdf['num_authors'] = authors_longdf['AU'].apply(lambda x: len(x.split("; ")))
authors_longdf.head()

,AU,TI,SO,UT,CR,NR,TC,Z9,author_pos,author,num_authors
0,"Adekola, J; Clelland, D",Two sides of the same coin: Business resilienc...,JOURNAL OF CONTINGENCIES AND CRISIS MANAGEMENT,WOS:000479973700001,"Adekola J, 2018, INT J DISAST RISK RE, V31, P4...",49,35,37,1,"Adekola, J",2
1,"Mochizuki, J; Keating, A; Liu, W; Hochrainer-S...",An overdue alignment of risk and resilience? A...,DISASTERS,WOS:000426851400008,"Ainuddin S, 2012, NAT HAZARDS, V63, P909, DOI ...",136,31,31,1,"Mochizuki, J",5
2,"Olsson, P; Galaz, V; Boonstra, WJ",Sustainability transformations: a resilience p...,ECOLOGY AND SOCIETY,WOS:000347440700010,"Adger WN, 2005, ECOL SOC, V10; Anderies JM, 20...",127,317,318,1,"Olsson, P",3
3,"Saikia, P; Beane, G; Garriga, RG; Avello, P; E...",City Water Resilience Framework: A governance ...,SUSTAINABLE CITIES AND SOCIETY,WOS:000800697400001,"Adams C.A., 2020, SUSTAINABLE DEV GOAL; Alegre...",39,16,16,1,"Saikia, P",11
4,"Viscu, LI",Resilience indicators in psychotherapy,SECOND WORLD CONGRESS ON RESILIENCE: FROM PERS...,WOS:000342208700230,"[Anonymous], 1997, PSYCHOTHERAPY IMPOSS; [Anon...",5,1,1,1,"Viscu, LI",1

In [131]:
authors_longdf = authors_longdf.sort_values(by = ['UT', 'author_pos'])
authors_longdf.head(10)

,AU,TI,SO,UT,CR,NR,TC,Z9,author_pos,author,num_authors
326,"Peterson, GD",Estimating resilience across landscapes,CONSERVATION ECOLOGY,WOS:000177892600005,"[Anonymous], 2001, PANARCHY UNDERSTANDI; [Anon...",25,64,65,1,"Peterson, GD",1
405,"Bowen, DJ; Morasca, AA; Meischke, H",Measures and correlates of resilience,WOMEN & HEALTH,WOS:000187079500005,"[Anonymous], 1992, MANUAL LIFE ATTITUDE; Bowen...",17,20,20,1,"Bowen, DJ",3
905,"Bowen, DJ; Morasca, AA; Meischke, H",Measures and correlates of resilience,WOMEN & HEALTH,WOS:000187079500005,"[Anonymous], 1992, MANUAL LIFE ATTITUDE; Bowen...",17,20,20,2,"Morasca, AA",3
1405,"Bowen, DJ; Morasca, AA; Meischke, H",Measures and correlates of resilience,WOMEN & HEALTH,WOS:000187079500005,"[Anonymous], 1992, MANUAL LIFE ATTITUDE; Bowen...",17,20,20,3,"Meischke, H",3
217,"Makhnach, AV",RESILIENCE AS INTERDISCIPLINARY NOTION,PSIKHOLOGICHESKII ZHURNAL,WOS:000209039700007,"ABRAMOVA I, 2000, ZHURN PSIHIATRII I M, P42; A...",82,3,3,1,"Makhnach, AV",1
65,"Vance, A; Pendergast, D; Garvis, S",Teaching resilience: a narrative inquiry into ...,PASTORAL CARE IN EDUCATION,WOS:000210532500002,"[Anonymous], 1996, EDUC RESEARCHER, DOI DOI 10...",40,10,10,1,"Vance, A",3
565,"Vance, A; Pendergast, D; Garvis, S",Teaching resilience: a narrative inquiry into ...,PASTORAL CARE IN EDUCATION,WOS:000210532500002,"[Anonymous], 1996, EDUC RESEARCHER, DOI DOI 10...",40,10,10,2,"Pendergast, D",3
1065,"Vance, A; Pendergast, D; Garvis, S",Teaching resilience: a narrative inquiry into ...,PASTORAL CARE IN EDUCATION,WOS:000210532500002,"[Anonymous], 1996, EDUC RESEARCHER, DOI DOI 10...",40,10,10,3,"Garvis, S",3
413,"Simon, JB; Murphy, JJ; Smith, SM",Understanding and Fostering Family Resilience,FAMILY JOURNAL,WOS:000211221900007,"[Anonymous], 2003, POSITIVE PSYCHOL ASS; [Anon...",41,71,74,1,"Simon, JB",3
913,"Simon, JB; Murphy, JJ; Smith, SM",Understanding and Fostering Family Resilience,FAMILY JOURNAL,WOS:000211221900007,"[Anonymous], 2003, POSITIVE PSYCHOL ASS; [Anon...",41,71,74,2,"Murphy, JJ",3

In [132]:
authors_longdf.to_csv(Path(folder_path, "resilience_author-pos.csv", index = False), encoding = 'utf-8')